### ISSUE TITLE
Which is the zone?

### ISSUE THREAD

**Issue by TomOnTime** [Cyb3r-Jak3/actions-cloudflare-pages#2]
Hi there!

Thanks for providing this action.  Sadly I'm having some problems getting it to work.

I'm getting this error:

```
Error: Error making purge request. Request failed with status code 404 {"result":null,"success":false,"errors":[{"code":8000032,"message":"Unable to find a branch with the provided name"}],"messages":[]}
```

I set CLOUDFLARE_PROJECT to the name of the Cloudflare "pages" project (in this case, it is the name of the blog).  Maybe I should be specifying something else?

Thanks!
Tom

**Comment by Cyb3r-Jak3** [comment]
Hi Tom!

That looks to be an error with the settings in Cloudflare with the production branch. If you are using a non standard branch name check out this [guide](https://developers.cloudflare.com/pages/platform/github-integration#custom-branches)
